config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'home#index'
  resources :events
  resources :users, except: [:index]
  resources :sessions, only: [:new, :create, :destroy]
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  post 'attend_event', to: 'users#attend_event', as: 'attend_event'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  post 'send_friend_request', to: 'users#send_friend_request', as: 'friend_request'
  post 'accept_friend_request', to: 'users#accept_friend_request', as: 'accept_request'
  post 'decline_friend_request', to: 'users#decline_friend_request', as: 'decline_request'
  post 'remove_friend', to: 'users#remove_friend', as: 'remove_friend'
  post 'leave_event', to: 'events#leave_event', as: 'leave_event'
  post 'leave_event_show', to: 'users#leave_event_show', as: 'leave_event_show'
  post 'attend_event_show', to: 'users#attend_event_show', as: 'attend_event_show'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
    validates :name, presence: true
    validates :date, presence: true
    validates :time, presence: true
    validates :location, presence: true

    validate :date_is_in_the_future
    
    has_many :user_events
    has_many :users, through: :user_events

    def datetime 
        DateTime.new(self.date.year, self.date.month, self.date.day, self.time.hour, self.time.min, self.time.sec, self.time.zone)
    end

    def date_is_in_the_future
        
        if date && time
            if self.datetime < DateTime.now
                if self.date < DateTime.now.to_date
                    errors.add(:date ,"cant be in the past")
                elsif self.time  < Time.now
                    errors.add(:time, "has already passed")
                end
            end
        end
    end
end

app/models/user.rb
class User < ApplicationRecord
  has_friendship
  has_many :user_events
  has_many :events, through: :user_events

  has_secure_password
  
  validates :name, presence: true
  validates :email, presence: true, confirmation: true
  validates :email, uniqueness: true

  def created_events
    Event.all.select {|event| event.creator_id == self.id}
  end

  def upcoming_events
    self.events.select {|event| event.datetime >= DateTime.now.new_offset(0)}
  end
end

app/models/user_event.rb
class UserEvent < ApplicationRecord
    belongs_to :user
    belongs_to :event
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :current_user, :logged_in?, :attending_event?, :myself?, :friend?
    def current_user
      if session[:user_id]
        @current_user ||= User.find(session[:user_id])
      else
        @current_user = nil
      end
    end

    def logged_in?
      !!current_user
    end

    def attending_event?(event_id)
      if logged_in?
        @user = current_user
        @user.events.map {|event| event.id}.include?(event_id)
      end
    end

    def myself?(user_id)
      current_user.id == user_id
    end

    def friend?(friend_id)
      @user = current_user
      @user.friends.include?(User.find(friend_id))
    end
    
end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  def index
    @events = Event.all
  end

  def new
    @event = Event.new
  end
  
  def show
    find_event
    find_creator
  end

  def create
    @event = Event.new(event_params)
    if @event.valid?
      @event.save
      flash[:success] = "Event successfully created"
      current_user.events << @event
      redirect_to @event
    else
      flash[:errors] = @event.errors.full_messages
      redirect_to new_event_path
    end
  end

  def edit
    find_event
  end
  
  def update
    find_event
      if @event.update_attributes(event_params)
        flash[:success] = "Event was successfully updated"
        redirect_to @event
      else
        flash[:error] = "Something went wrong"
        render 'edit'
      end
  end
  
  def destroy
    find_event
    if @event.destroy
      flash[:success] = 'Event was successfully deleted.'
      redirect_to events_url
    else
      flash[:error] = 'Something went wrong'
      redirect_to events_url
    end
  end

  def leave_event
    @event = Event.find(params[:event_id])
    current_user.events.delete(@event)
    redirect_to events_path
  end
  
  private

  def event_params 
    params.require(:event).permit(:name, :date, :time, :description, :location, :creator_id)
  end

  def find_event
    @event = Event.find(params[:id])
  end
  
  def find_creator
    find_event
    @creator = User.find(@event.creator_id)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  layout "home_page"
  
  def index
    @events = Event.all
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
    end

    def create
      user = User.find_by(email: params[:email])
      if user && user.authenticate(params[:password])
        session[:user_id] = user.id
        redirect_to user_path(user), notice: "Logged in!"
      else
        flash.now[:alert] = "Email or password is invalid"
        render "new"
      end
    end

    def destroy
      session[:user_id] = nil
      redirect_to root_url, notice: "Logged out!"
    end
    
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def new
        @user = User.new
    end

    def create
      @user = User.new(user_params)
      if @user.save
        session[:user_id] = @user.id
        redirect_to user_path(@user), notice: "Thank you for signing up!"
      else
        flash[:errors] = @user.errors.full_messages
        redirect_to signup_path
      end
    end

    def edit
      @user = current_user
    end
    
    def update
      @user = current_user
      @user.assign_attributes(user_params)
      if @user.valid?
        @user.save
        redirect_to user_path(@user), notice: "You have successfully edited your profile"
      else
        flash[:errors] = @user.errors.full_messages
        redirect_to edit_user_path
      end
    end

    def show
      @user = User.find_by(id: params[:id])
      @friends = @user.friends
    end

    def attend_event
      if logged_in?
        @user = current_user
        @user.events << Event.find(params[:event_id])
        redirect_to events_path
      else
        redirect_to login_path
      end
    end

    def attending_event?(event_id)
      current_user
      @user.events.include?(Event.find(event_id))
    end

    def send_friend_request
      @user = current_user
      @user.friend_request(User.find(params[:request_id]))
      redirect_to @user
    end

    def accept_friend_request
      @user = current_user
      @user.accept_request(User.find(params[:request_id]))
      redirect_to @user
    end

    def decline_friend_request
      @user = current_user
      @user.decline_request(User.find(params[:request_id]))
      redirect_to @user
    end

    def remove_friend
      @user = current_user
      @user.remove_friend(User.find(params[:request_id]))
      redirect_to @user
    end

    def attend_event_show
      if logged_in?
        @user = current_user
        @event = Event.find(params[:event_id])
        @user.events << @event
        redirect_to @event
      else
        redirect_to login_path
      end
    end


  def leave_event_show
    @event = Event.find(params[:event_id])
    current_user.events.delete(@event)
    redirect_to @event
  end

    private

    def user_params
        params.require(:user).permit(:name, :bio, :email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/edit.html.erb
<div class="filler"></div>

<div class="signup-background">
  <div class="join-the-fun-signup">
    <h1 class="join-head-text">Edit Event</h1>
      <%= form_with model: @event do |f| %>
        <%= f.label "Event Name: " %>
        <%= f.text_field :name %><br />

        <%= f.label "Description: " %>
        <%= f.text_area :description %><br />

        <%= f.label "Date: " %>
        <%= f.date_field :date %><br />

        <%= f.label "Time: " %>
        <%= f.time_field :time %><br />

        <%= f.label "Event Location: " %>
        <%= f.text_field :location %><br />

        <%= f.hidden_field :creator_id, :value => current_user.id %>

        <%= f.submit %>
      <% end %>
      <%= link_to "Delete Event", event_path(@event), method: "delete", class: "delete-event-btn" %>
  </div> 
</div>

app/views/events/index.html.erb
<div class="filler"></div>

<h1 class="index-header">Are You Goin'?</h1>

<% @events.each do |event| %>
  <% if event.datetime > DateTime.now.new_offset(0) %>
    <div class="events-solstice">
      <div class="event-card">
        <div class="event-card-content">
          <div class="event-card-title">
            <p class="event-card-title-item item-link"><%= link_to event.name, event_path(event) %></p>
            <p class="event-card-title-item"><%= event.location %></p>
            <p class="event-card-title-item"><%=event.date.strftime("%m/%d/%y") %></p>
            <p class="event-card-title-item"><%= event.time.strftime("%I:%M %p") %></p>
          </div>
          <div class="event-card-desc">
            <p class="card-desc">Event Description:</p>
            <p class="card-text"><%= event.description %></p>
          </div>
          <div class="event-card-footer">
              <% if attending_event?(event.id) %>
            <p>You sure you goin'?</p>
              <%= button_to "I Ain't Goin'", leave_event_path, method: "post", params:{event_id: event.id} %>
            <% else %>
              <%= button_to "I'm Goin'", attend_event_path, method: "post", params:{event_id: event.id} %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
<% end %>

app/views/events/new.html.erb
<div class="filler"></div>

<div class="signup-background">
  <div class="join-the-fun-signup">
    <h1 class="join-head-text">Create New Event</h1>

    <%= form_with model: @event do |f| %>

     <% if flash[:errors] %>
        <div class="error_messages">
          <ul class="signup-errors">
            <% flash[:errors].each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <%= f.label "Event Name: " %>
      <%= f.text_field :name %><br />

      <%= f.label "Description: " %>
      <%= f.text_area :description %><br/>

      <%= f.label "Date: " %>
      <%= f.date_field :date %><br />

      <%= f.label "Time: " %>
      <%= f.time_field :time %><br />

      <%= f.label "Event Location: " %>
      <%= f.text_field :location %><br />

      <%= f.hidden_field :creator_id, :value => current_user.id %>

      <%= f.submit %>
    <% end %>
  </div> 
</div>

app/views/events/show.html.erb
<div class="filler"></div>

<div class="event-heading">
    <h1><%= @event.name %></h1>
    <h2>Created by: <%= link_to @creator.name.titleize, user_path(@creator) %></h2>
    <%if @creator == current_user %>
        <div class="edit-user-btn">
            <%= link_to "Edit Event", edit_event_path %>
        </div>
    <% end %>
</div>

<div class="event-content-grid">
    <div class="event-content">
        <% if attending_event?(@event.id) %>
            <div class="user-new-event-btn"><%= link_to "I Ain't Goin'", leave_event_show_path(:event_id => "#{@event.id}"), method: "post"%></div>
            <% else %>
            <div class="user-new-event-btn"><%= link_to "I'm Goin'", attend_event_show_path(:event_id => "#{@event.id}"), method: "post"%></div>
        <% end %>
        <h3><span>Location:</span> <%= @event.location %></h3>
        <h4><span>Date:</span> <%= @event.date.strftime("%m/%d/%y") %></h4>
        <h4><span>Time:</span> <%= @event.time.strftime("%I:%M %p") %></h4>
        <div class="event-description">
            <p><span>Description</span></p>
            <hr id="two" data-symbol="âœˆ">
            <p><%= @event.description %></p>
        </div>
        
    </div>
    <div class="attendees">
        <% if @event.users.count > 0 %>
            <h4 class="user-friends-heading">Who's Goin'</h4>
            <hr id="two" data-symbol="âœˆ">
            <% @event.users.each do |user| %>
                <div class="friend-display">
                    <%= link_to user.name, user %>
                </div>
            <% end %>
        <% else %>
            <div class="friend-display">
                <p>No one is going to this event yet.</p>
            </div>
        <% end %>
    </div>
</div>

app/views/home/index.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EventScheduler10</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link href="https://fonts.googleapis.com/css?family=Monoton&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Barlow:300,400,700|Permanent+Marker&display=swap" rel="stylesheet">
  </head>

  <body class="landing">
      <div class="hero-text-box">
          <h1>we Goin'</h1>
          <h2>The best place to arrange events</h2>
          <div class="home-btn-display">
            <div>
              <div class="btn btn-header">
                <%= link_to "Log In", login_path %>
              </div>
            </div>
            <div>
              <div class="btn btn-header" id="signup-btn">
                <%= link_to "Sign Up", signup_path %>
              </div>
            </div>
          </div>
      </div>
  </body>
  
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EventScheduler10</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.11.2/css/all.css" integrity="sha384-KA6wR/X5RY4zFAHpv/CnoG2UW1uogYfdnP67Uv7eULvTveboZJg0qUpmJZb5VqzN" crossorigin="anonymous">

    <link href="https://fonts.googleapis.com/css?family=Monoton&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Barlow:300,400,700|Permanent+Marker&display=swap" rel="stylesheet">
  </head>

  <header>
    <nav>
      <ul class="navbar sticky">
        
        <p class="logo"><%= link_to "WEGOIN'", events_path %></p>
        
        <% if current_user %>
          <li><%= link_to "Log Out", logout_path %></li>
          <li><%= link_to "Create Event", new_event_path %></li>
          <li> <a class="logged-in-user" href="<%= user_path(current_user) %>"><%= current_user.name.titleize %> <i class="fas fa-user-astronaut nav-icon"></i></a></li> 
        <% else %>
          <li><%= link_to "Log In", login_path %></li>
          <li><%= link_to "Sign Up", signup_path %></li>
        <% end %>
      </ul>
    </nav>
  </header>
  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/home_page.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EventScheduler10</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  
  <body>
    <%= yield %>
  </body>
</html>

app/views/users/edit.html.erb
<div class="filler"></div>

<div class="signup-background">
  <div class="join-the-fun-signup">
    <h1 class="join-head-text">Edit your profile</h1>

    <%= form_for @user do |f| %>
      <% if flash[:errors] %>
        <div class="error_messages">
          <h2>Form is invalid</h2>
          <ul>
            <% flash[:errors].each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div class="field">
        <%= f.label :name %>
        <%= f.text_field :name %>
      </div>
      <br>
      <div class="field">
        <%= f.label :bio %>
        <%= f.text_area :bio %>
      </div>
      <br>
      <div class="field">
        <%= f.label :email %>
        <%= f.email_field :email %>
      </div>
      <br>
      <div class="field">
        <%= f.label :password %>
        <%= f.password_field :password %>
      </div>
      <br>
      <div class="field">
        <%= f.label :password_confirmation %>
        <%= f.password_field :password_confirmation %>
      </div>
      <br>
      <div class="actions">
        <%= f.submit "Edit" %>
      </div>
    <% end %>  
  </div>
</div>

app/views/users/new.html.erb
<div class="signup-background">
  <div class="join-the-fun-signup">
    <h1 class="join-head-text">Sign Up</h1>

    <%= form_for @user do |f| %>
      <% if flash[:errors] %>
        <div class="error_messages">
          <ul class="signup-errors">
            <% flash[:errors].each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div class="field">
        <%= f.label :name %>
        <%= f.text_field :name %>
      </div>
      <br>
      <div class="field">
        <%= f.label :bio %>
        <%= f.text_area :bio %>
      </div>
      <br>
      <div class="field">
        <%= f.label :email %>
        <%= f.email_field :email %>
      </div>
      <br>
      <div class="field">
        <%= f.label :password %>
        <%= f.password_field :password %>
      </div>
      <br>
      <div class="field">
        <%= f.label :password_confirmation %>
        <%= f.password_field :password_confirmation %>
      </div>
      <br>
      <div class="actions">
        <%= f.submit "Sign Up" %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="filler"></div>

<div class="user-heading">
  <div class="user-heading-left">
    <h1 class="user-name"><%= @user.name.titleize %>'s Page</h1>
    <h2 class="user-email"><%= @user.email %></h2>
    <% if myself?(@user.id) && logged_in? %>
      <div class="edit-user-btn">
        <%= link_to "Edit Profile", edit_user_path %>
      </div>
    <% elsif !myself?(@user.id) && !friend?(@user.id) %>
      <div class="edit-user-btn">
        <%= link_to "Add Friend", friend_request_path(request_id: @user.id), method: :post %>
      </div>
    <% elsif !myself?(@user.id) && friend?(@user.id) %>
      <div class="edit-user-btn">
        <%= link_to "Remove Friend", remove_friend_path(request_id: @user.id), method: :post %>
      </div>
    <% end %>
  </div>
  <div class="user-heading-right">
    <h2 class="user-bio-label">About <%= @user.name %>: </h2>
    <p class="user-bio"><%= @user.bio %></p>
  </div>
</div>

<div class="user-content-grid">
  <div class="user-events">
    <div class="user-new-event-btn"><%= link_to "Create Event", new_event_path %></div>
    <h2 class="user-events-heading">Upcoming Events</h2>
    <% if @user.upcoming_events.count > 0 %>
        <% @user.upcoming_events.each do |event| %>
          <%# <% if event.datetime >= DateTime.now %>
            <div class="event-card">
              <div class="event-card-content">
                <div class="event-card-title">
                  <p class="event-card-title-item item-link"><%= link_to event.name, event_path(event) %></p>
                  <p class="event-card-title-item"><%= event.location %></p>
                  <p class="event-card-title-item"><%=event.date.strftime("%m/%d/%y") %></p>
                  <p class="event-card-title-item"><%= event.time.strftime("%I:%M %p") %></p>
                </div>
                <div class="event-card-desc">
                  <p class="card-desc">Event Description:</p>
                  <p class="card-text"><%= event.description %></p>
                </div>
                <% if attending_event?(event.id) %>
                  <div class="event-card-footer">
                    <%= button_to "I Ain't Goin", leave_event_path, method: "post", params:{event_id: event.id} %>
                  </div>
                <% else %>
                  <div class="event-card-footer">
                    <%= button_to "I'm Goin", attend_event_path, method: "post", params:{event_id: event.id} %>
                  </div>
                <% end %>
              </div>
            </div>
          <%# <% end %>
        <% end %>
      <div class="user-all-event-btn"><%= link_to "All Events", events_path %></div>
    <% else %>
      <div class="no-events-display">
        <h2>Why ain't you goin' anywhere?</h2>
        <%= link_to "Go Somewhere!",  events_path %>
      </div>
        
    <% end %>
  </div>
  <div class="user-friends">
    <p class="user-friends-heading">Friends</p>
    <hr id="two" data-symbol="✈">
    <% if myself?(@user.id) && current_user.requested_friends.count > 0 %>
      <% current_user.requested_friends.each do |friend| %>
      <div class="friend-display">
        <%= link_to friend.name, user_path(friend), class: "user-friend" %>
        <%= button_to "Accept", accept_request_path, method: "post", params: {request_id: friend.id} %>
        <%= button_to "Decline", decline_request_path, method: "post", params: {request_id: friend.id} %>
      </div>
      <% end %>
    <% end %>
    <% if @friends.count > 0 %>
        <% @friends.each do |friend| %>
          <div class="friend-display">
            <%= link_to friend.name, user_path(friend), class: "user-friend" %>
            <% if myself?(@user.id) %>
              <%= button_to "Remove Friend", remove_friend_path, method: "post", params: {request_id: friend.id}, class: "user-friend-remove" %>
            <% end %>
          </div>
          
        <% end %>
    <% else %>
      <div class="friend-display">
        <p>Go to events to make some friends.</p>
      </div>
    <% end %>
  </div>
  
</div>

<br> 


<br>
<% if @user.events.count > 0 %>
<div class="wrap-collabsible">
  <input id="collapsible" class="toggle" type="checkbox">
  <label for="collapsible" class="lbl-toggle">Past Events</label>
  <div class="collapsible-content">
    <div class="content-inner">
      <p>
        <% if @user.events.count > 0 %>
        <% @user.events.each do |event| %>
          <% if event.datetime < DateTime.now.new_offset(0) %>
            <div class="event-card">
              <div class="event-card-content">
                <div class="event-card-title">
                  <p class="event-card-title-item item-link"><%= link_to event.name, event_path(event) %></p>
                  <p class="event-card-title-item"><%=event.date.strftime("%m/%d/%y") %></p>
                  <p class="event-card-title-item"><%= event.time.strftime("%I:%M %p") %></p>
                </div>
              </div>
            </div>
          <% end %>
        <% end %>
        <% end %>
    </div>
  </div>
</div>
<% end %>